#modify the file to run again 1
on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    #- name: azure az update
      #uses: azure/CLI@v1
      #with:
        #aucliversion: 2.30.0
        #inlinescript: |
          #az --version
          #az cloud set --name AzureChinaCloud
          #az login -u bulu@mcpod.partner.onmschina.cn -p Password@345 --debug
      
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        environment: 'AzureChinaCloud'
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage -h
