#modify the file to run again 1
on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: azure az update
      uses: azure/CLI@v1
      with:
        aucliversion: 2.30.0
        inlinescript: |
          az --version
          az cloud set --name AzureChinaCloud
      
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: '{"appId": "5735fa60-62c4-4b04-899f-f8b0d29e9fbb","displayName": "azure-cli-2022-12-29-08-14-22","name": "5735fa60-62c4-4b04-899f-f8b0d29e9fbb","password": "bmJYPpjrxmA0kqYzlSto..d2gStErum8m7","tenant": "954ddad8-66d7-47a8-8f9f-1316152d9587"}'
        environment: AzureChinaCloud
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage -h
