#modify the file to run again
on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Sample Azure action
      with: # Set Azure credentials secret as an input
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
      env: # Or as an environment variable
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: AzureChinaCloud
    
